language: node_js
node_js:
- stable
script: yarn test
after_success: yarn build
deploy:
  provider: pages
  local_dir: /home/travis/build/sensebox/opensensemap-widget/dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
